### ISSUE TITLE
Layout/UI improvements

### ISSUE THREAD

**Issue by WillemSleegers** [MicheleNuijten/statcheck-web#21]
A few things I noticed that we may or may not want to look at to improve:
- [x] Add more white space at the bottom of each page
- [x] Remove 'About' from 'About/FAQ' in the navigation bar
- [x] Just have 'FAQ' as the main title of the FAQ page
- [x] The FAQ orange color is quite bright; probably better to make it lighter
- [x] Lower the orange on the Contact cards
- [ ]  it's hard to see on which page/tab you are. was clearer in previous version
- [x] the mouse-over-color-change of the "Browse" button is hard to see, too subtle
- [x] in the FAQ, the difference between text and the next header is very small. I'd like a bigger contrast between the FAQ accordion headers and the inside text
- [x] the "contact" page is very plain now the panel is gone

**Comment by WillemSleegers** [comment]
Let's switch to Bootstrap 5.

**Comment by WillemSleegers** [comment]
I created a new branch to replace the FAQ; please take a look to see whether you like it!

**Comment by WillemSleegers** [comment]
I think I fixed all the issues for now, so I'm closing this.

**Comment by MicheleNuijten** [comment]
Nice! One more minor thing:

- [ ] max-width of text & table on home page should be smaller

**Comment by WillemSleegers** [comment]
I addressed most of these issues, except for the navbar one. I think it's fine like this actually.

**Comment by MicheleNuijten** [comment]
yep, let's keep it like this
