### ISSUE TITLE
The statcheck images in the FAQ have an incorrectly placed comma, at least on my screen

### ISSUE THREAD

**Issue by MicheleNuijten** [MicheleNuijten/statcheck-web#22]
The comma is misplaced in some conditions. In addition, there are a few other issues as well:

- [x] Maybe add some more space below the calculator in the statcheck images and/or reduce the space above the statistics
- [x] The second image in the FAQ has text going outside of the rectangular bounds  
- [x] Fix similar issues in other FAQ images
- [x]   Maybe make all rectangles in the FAQ image slightly rounded

**Comment by MicheleNuijten** [comment]
This does work on my computer (windows; google chrome & Rstudio viewer). The images are svg files now, maybe the vectorization works differently on different OS or browsers

**Comment by WillemSleegers** [comment]
If you want to use an .svg, it might be better to use the `svg` HTML tag, not an `img` with an .svg as its source.

**Comment by MicheleNuijten** [comment]
solved: edited images & saved as png instead of svg
