### ISSUE TITLE
Build in support for new version of statcheck

### ISSUE THREAD

**Issue by WillemSleegers** [MicheleNuijten/statcheck-web#24]
Add support for the new version of statcheck so this app won't break when the new version of statcheck is released. 

The most important change will be the names of the columns in the statcheck results, so let's add in code to check which names are in the data frame and change accordingly.

**Comment by MicheleNuijten** [comment]
Done: see the branch compatibility-new-statcheck. I checked it on my computer with both the statcheck version on CRAN and the new version, and both seem to work. If it works for you, this branch can be merged with main.

**Comment by WillemSleegers** [comment]
I added it to the fix-ui-issues brand and also adapted it so we don't need to rely on the `dplyr` package.
