### ISSUE TITLE
is the app still deleting uploaded papers every 5 mins?

### ISSUE THREAD

**Issue by MicheleNuijten** [MicheleNuijten/statcheck-web#6]
in the faq it says: 

Do you maintain a copy of analyzed papers or results?
No. Once all files have been analyzed, the source PDF(s) or HTML files are deleted. Outside of simple server and activity logs, no record of results is maintained. We do not maintain any archive of submitted files. **To ensure privacy, a maintenance script that deletes any uploaded documents is run every five minutes. The code run on this server is available here.**

I don't think we built that in this version, did we? And should we? Are the papers stored anywhere otherwise?

**Comment by WillemSleegers** [comment]
No
